In [1]:
using DataFrames, Optim, Revise, Serialization

In [2]:
string(@__DIR__) in LOAD_PATH || push!(LOAD_PATH, @__DIR__);

In [3]:
using BLPmodule; const m = BLPmodule;

In [4]:
df = deserialize("jls/df.jls");
pars = deserialize("jls/pars.jls");
ec = deserialize("jls/ec.jls");

---

In [5]:
function g!(storage::Array, θ2::Array)
    storage[:] = m.gmm_grad(θ2, ec, pars, X1)
end

g! (generic function with 1 method)

In [6]:
# linear characteristics (staffing variables):
X1 = vcat(transpose.([ec.firms[i].X for i in eachindex(ec.firms)])...)
Z = X1;

In [7]:
initial_δ = zeros(length(ec.firms), 1);

In [22]:
pars = deserialize("jls/pars.jls");
m.gmm_lm([10.,10.], ec, pars, X1)

obj = 150.80675378431536
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:22)
pars.σ = [10.0, 10.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:23)


150.80675378431536

In [12]:
m.gmm_lm([1.,1.], ec, pars, X1)

obj = 151.19673434313256
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:22)


151.19673434313256

In [23]:
pars.σ

2-element Vector{Float64}:
 1.0
 1.0

In [20]:
m.gmm_grad([2.,2.], ec, pars, X1)

pars.σ[1] = 1.0
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:30)


grad = [-121.22994827721004; -4.122342967979769]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:83)


2×1 Matrix{Float64}:
 -121.22994827721004
   -4.122342967979769

In [16]:
pars = deserialize("jls/pars.jls");
m.gmm_grad_alt([1.,1.], ec, pars, X1)

gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsuppor

110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facs

110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facs

110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facsupport/zhli/blp-quantities/BLPmodule/gmm.jl:110)
gradj[jj] = [0.0, 0.0]
(in /users/facs

2-element Vector{Float64}:
 0.0
 0.0

In [17]:
initial_θ2 = [10.,20.]
pars = deserialize("jls/pars.jls");
res = optimize(θ2 -> m.gmm_lm(θ2, ec, pars, X1), g!, initial_θ2, LBFGS())

δ[1] = 0.0
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:79)


grad = [0.0; 0.0]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:84)
obj = 150.89460765482497
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


 * Status: success

 * Candidate solution
    Final objective value:     1.508946e+02

 * Found with
    Algorithm:     L-BFGS

 * Convergence measures
    |x - x'|               = 0.00e+00 ≤ 0.0e+00
    |x - x'|/|x'|          = 0.00e+00 ≤ 0.0e+00
    |f(x) - f(x')|         = NaN ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = NaN ≰ 0.0e+00
    |g(x)|                 = 0.00e+00 ≤ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    0
    f(x) calls:    1
    ∇f(x) calls:   1


In [15]:
initial_θ2 = [1.,1.]

pars = deserialize("jls/pars.jls");
res = optimize(θ2 -> m.gmm_lm(θ2, ec, pars, X1), g!, initial_θ2, LBFGS())

θ2 = [1.0, 1.0]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.6906467099492097; -0.23862404002686533]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 303.2455807486537
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [-7.985913587649435, -2.118980246319886]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8291268772894276; -0.24072463157591018]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 399.67644347085337
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [-3.4929567938247175, -0.559490123159943]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8217679853456918; -0.2264794835658468]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 391.9805397420546
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [-1.2464783969123587, 0.22025493842002852]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8188995655069673; -0.2229277626396532]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 391.15435041142774
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [-0.12323919845617937, 0.6101274692100143]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8186407541413621; -0.2211988801349134]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 392.5059495623277
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.3570488422818944, 0.7768338254412438]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8188165669460328; -0.2200146245194895]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 393.9924931758216
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.8596453177599543, 0.9512833639990835]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8191518956893079; -0.21910348038930483]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 395.3779247060183
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.9814099131651712, 0.9935474436683995]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8192898759578587; -0.21833732082327628]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 396.4622931363402
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.9977533399596846, 0.9992201918906085]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8193363570468727; -0.21768781524788872]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 397.3470004140032
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.999731761004125, 0.9999068951508084]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8193645838098523; -0.2171326211122545]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 398.1050749799539
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.9999680312602982, 0.9999889037584596]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8193877448912648; -0.2166512082417803]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 398.7653625049258
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.9999961918791519, 0.9999986782141198]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8194080486233928; -0.21622945040153152]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 399.3458723574787
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.9999995465165856, 0.999999842597439]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8194261090647132; -0.2158570738579867]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 399.86003797311054
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.9999999460115088, 0.999999981260777]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8194422658169449; -0.21552623749472744]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 400.3182708973455
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.9999999935739493, 0.9999999977695395]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8194567745540525; -0.21523078158012143]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 400.72878200716764
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.9999999992352819, 0.9999999997345689]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8194698440024399; -0.21496576874733142]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 401.0981471661227
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.9999999999090124, 0.9999999999684185]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8194816488498884; -0.214727177529494]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 401.4317114611419
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.9999999999891759, 0.999999999996243]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8194923370911087; -0.2145116876996429]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 401.73388044961143
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.9999999999987125, 0.9999999999995531]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.81950203516772; -0.21431652538425816]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 402.0083319393651
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.9999999999998469, 0.9999999999999468]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8195108518444395; -0.21413934887612307]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 402.25817175438056
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.9999999999999818, 0.9999999999999937]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.819518881232087; -0.21397816296919503]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 402.48604975468714
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.9999999999999978, 0.9999999999999992]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8195262051911228; -0.21383125370650624]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 402.6942473938014
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [0.9999999999999998, 0.9999999999999999]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.819532895267828; -0.21369713798716572]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 402.884744680087
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


θ2 = [1.0, 1.0]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:11)
θ1 = [-0.8195390142695097; -0.21357452414933598]
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:19)
obj = 403.0592720680424
(in /mnt/staff/zhli/blp-quantities/BLPmodule/gmm.jl:22)


 * Status: failure (line search failed)

 * Candidate solution
    Final objective value:     4.030593e+02

 * Found with
    Algorithm:     L-BFGS

 * Convergence measures
    |x - x'|               = 0.00e+00 ≤ 0.0e+00
    |x - x'|/|x'|          = 0.00e+00 ≤ 0.0e+00
    |f(x) - f(x')|         = 9.98e+01 ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 2.48e-01 ≰ 0.0e+00
    |g(x)|                 = 7.74e+01 ≰ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    1
    f(x) calls:    24
    ∇f(x) calls:   24


In [18]:
size(inv(X1' * X1))

(2, 2)

In [15]:
println(Optim.minimizer(res))
println(Optim.initial_state(res))

[2.0, 3.0]
[2.0, 3.0]


---