In [2]:
using DataFrames, LinearAlgebra, Distributions, Revise, Serialization, DebuggingUtilities

In [3]:
const datadir = "/export/storage_adgandhi/MiscLi/factract";
string(@__DIR__) in LOAD_PATH || push!(LOAD_PATH, @__DIR__)
using BLPmodule; const m = BLPmodule;

---

## Computation

In [4]:
Threads.nthreads()

32

In [5]:
testmodes = ["", "_FL", "_FL17"]
testmode = testmodes[3]################# EDIT THIS ##################
config_tag = "111"
pars = deserialize("$datadir/analysis/pars$config_tag$testmode.jls");
ec = deserialize("$datadir/analysis/ec$config_tag$testmode.jls");

In [6]:
nD = size(ec.tracts[1].D)[2]
σ = ones(nD); #initialize non-linear coef

In [30]:
pars = deserialize("$datadir/analysis/pars$config_tag$testmode.jls");
ec = deserialize("$datadir/analysis/ec$config_tag$testmode.jls");

deltas, q_iter = m.compute_deltas(ec, pars, σ, max_iter=1000, verbose=true, tol = 1e-4);


dist = 9.771774789868459e-5, iterations = 304


In [22]:
m.mean_inside_share(ec)

0.2983009625485831

In [11]:
using BenchmarkTools

In [24]:
pars = deserialize("$datadir/analysis/pars$config_tag$testmode.jls");
ec = deserialize("$datadir/analysis/ec$config_tag$testmode.jls");

it = 1
@time m.compute_deltas(ec, pars, σ, max_iter=it, verbose=false);

  0.148549 seconds (187.94 k allocations: 388.520 MiB)


In [25]:
pars = deserialize("$datadir/analysis/pars$config_tag$testmode.jls");
ec = deserialize("$datadir/analysis/ec$config_tag$testmode.jls");

it = 10
@time m.compute_deltas(ec, pars, σ, max_iter=it, verbose=false);

  0.771618 seconds (649.23 k allocations: 456.010 MiB, 76.38% gc time)


In [25]:
pars = deserialize("$datadir/analysis/pars$config_tag$testmode.jls");
ec = deserialize("$datadir/analysis/ec$config_tag$testmode.jls");

it = 1000
@time m.compute_deltas(ec, pars, σ, max_iter=it, verbose=false);

  4.324013 seconds (21.44 M allocations: 2.841 GiB, 2.01% gc time, 16.88% compilation time)


___
continued in `gmm.ipynb`

In [ ]:
# testing

In [26]:
n_firms = length(ec.firms)
j_indexer, t_indexer, positionin = m.create_indices(ec.tracts, n_firms);
share = [tt.shares for tt in ec.tracts]
mktq = [tt.q for tt in ec.tracts]
X_dc = [t.X[:,[1]] for t in ec.tracts];


In [42]:
η_dc = m.compute_elasticity(X_dc, 1., share, mktq, t_indexer, positionin, n_firms);

In [11]:
n_firms

421

In [13]:
j_indexer[12]

10-element Vector{Int64}:
   1
  60
  72
  76
  90
 275
 368
 398
 404
 410

In [34]:
t_indexer[12]

310-element Vector{Int64}:
  611
  612
  613
  618
  647
  648
  649
  650
  651
  652
    ⋮
 1823
 1824
 1825
 1826
 1827
 1828
 1829
 1830
 1831

In [39]:
mktq[t_indexer[12]]

310-element Vector{Matrix{Float64}}:
 [0.1781505983598531; 0.29768592276121975; … ; 0.0014458767128792817; 0.05929284513772435]
 [0.2681498637755776; 0.04484675330218255; … ; 0.0007938043689239894; 0.11733868439385343]
 [0.02544748625117383; 0.03744174999176627; … ; 0.013696051124753585; 0.02579290012134431]
 [0.03461333379603348; 0.04097940481631487; … ; 0.011267292632608181; 0.0209212244439876]
 [0.0151187973333018; 0.07252489705155911; … ; 0.0028376424671551766; 0.1354106922074412]
 [0.006054583990878407; 0.021247062227076226; … ; 0.0021874480763594004; 0.05310532744958765]
 [0.000766656391162099; 0.0027704973164145038; … ; 0.003512750824801319; 0.013089560922855658]
 [0.003909744745121288; 0.015290321455764458; … ; 0.0011094511861786847; 0.03533522422581457]
 [0.0018584441888977623; 0.005229681322769517; … ; 0.0007069476663110365; 0.011198012650422407]
 [0.03662173824167526; 0.1124005353788572; … ; 0.012881872455682283; 0.13443825280851507]
 ⋮
 [2.9041435032027487; 0.57360841427445

In [17]:
size(positionin)

(421, 4257)